name: Blank Issue
description: Create a new issue from scratch
title: "[Issue]: "
labels: ["triage needed"]
body:
  - type: textarea
    id: body
    attributes:
      label: "triage needed"
      placeholder: "Type your description here..."
    validations:
      required: false
