blank_issues_enabled: true
contact_links:
  - name: "Blank issue"
    url: "https://github.com/shellatol-commits-mods/ShellAtolMod/issues?q=is%3Aissue%20label%3A%22triage%20needed%22"
    about: "Create a new issue from scratch"
